### PR TITLE
data: update hipal

### PR DESCRIPTION
**Pull request by danielasubotic**

### CODE REVIEW

**Review by editio — APPROVED** [review]
👍  thank you, Daniela

**Comment by mpro7** [comment]
@danielasubotic I have changed the PR prefix to `data`. In this (new) repo, we introduced this prefix to highlight data manipulation in release notes. So please use this one with proper title.

**Comment by BalduinLandolt** [comment]
> @danielasubotic I have changed the PR prefix to `data`. In this (new) repo, we introduced this prefix to highlight data manipulation in release notes. So please use this one with proper title.

@mpro7  I thought so as well, but then I double checked and couldn't see "data" in here: https://github.com/dasch-swiss/dsp-meta/blob/main/.github/release-please/config.json  
Was this lost on the way, maybe? could you re-add it?

**Comment by mpro7** [comment]
@BalduinLandolt I have no idea how this is possible, but it seems so. @danielasubotic could wait with merging this PR then :) I will try to fix it anyway, including rebase and re-adding this fix.

**Pull request merged**
